import React, { useState } from 'react';

const Education = ({ educationalContent }) => {
  const [activeTab, setActiveTab] = useState('fundamentals');
  const [expandedSection, setExpandedSection] = useState(null);

  const toggleSection = (sectionId) => {
    setExpandedSection(expandedSection === sectionId ? null : sectionId);
  };

  const educationalTabs = {
    fundamentals: {
      title: 'TMS Fundamentals',
      icon: '🧠',
      sections: [
        {
          id: 'what-is-tms',
          title: 'What is Tension Myositis Syndrome?',
          preview:
            'Understanding the groundbreaking discovery that revolutionized chronic pain treatment',
          content: `
            <p>Tension Myositis Syndrome (TMS) is a condition discovered by Dr. John Sarno where emotional stress and psychological tension manifest as real physical pain. This revolutionary understanding has helped thousands of people recover from chronic pain conditions that traditional medicine struggled to treat effectively.</p>
            
            <h4>The Core Discovery</h4>
            <p>Dr. Sarno observed that many patients with severe back pain had minimal or no structural abnormalities that could explain their level of suffering. Through careful observation and treatment, he discovered that the unconscious mind creates physical symptoms as a way to distract from emotional pain and psychological stress.</p>
            
            <h4>How TMS Works</h4>
            <p>The unconscious mind, in an attempt to protect us from experiencing difficult emotions, creates a physical distraction. This process involves:</p>
            <ul>
              <li><strong>Oxygen Deprivation:</strong> Mild reduction of blood flow to muscles, nerves, and tendons</li>
              <li><strong>Muscle Tension:</strong> Chronic contraction of muscle groups</li>
              <li><strong>Nerve Sensitivity:</strong> Heightened sensitivity in the nervous system</li>
              <li><strong>Fear Reinforcement:</strong> The fear of pain perpetuates the cycle</li>
            </ul>
            
            <h4>Why This Happens</h4>
            <p>TMS typically affects people who are:</p>
            <ul>
              <li>Perfectionists with high standards for themselves</li>
              <li>People-pleasers who have difficulty expressing anger</li>
              <li>Highly responsible individuals who put others' needs first</li>
              <li>Those who have experienced trauma or significant stress</li>
              <li>Individuals with a strong need for control</li>
            </ul>
            
            <h4>The Good News</h4>
            <p>TMS is completely reversible. Once you understand that your pain is generated by your mind (not your body structure), and you address the underlying emotional issues, the pain typically resolves. This process requires patience, self-compassion, and often a fundamental shift in how you relate to your emotions and stress.</p>
          `,
        },
        {
          id: 'mind-body-connection',
          title: 'The Mind-Body Connection',
          preview:
            'How emotions directly influence physical health and pain perception',
          content: `
            <p>The mind-body connection is not just a philosophical concept—it's a scientifically proven reality that forms the foundation of TMS theory. Understanding this connection is crucial for healing.</p>
            
            <h4>Scientific Evidence</h4>
            <p>Modern neuroscience has confirmed what Dr. Sarno observed clinically:</p>
            <ul>
              <li><strong>Brain Imaging:</strong> Studies show that emotional pain activates the same brain regions as physical pain</li>
              <li><strong>Stress Response:</strong> Chronic stress triggers the release of hormones that cause inflammation and muscle tension</li>
              <li><strong>Placebo Effect:</strong> The mind's ability to heal through belief demonstrates the power of psychological factors</li>
              <li><strong>Neuroplasticity:</strong> The brain can rewire itself, including pain pathways</li>
            </ul>
            
            <h4>How Emotions Become Physical Symptoms</h4>
            <p>The process typically follows this pattern:</p>
            <ol>
              <li><strong>Emotional Trigger:</strong> A stressful event or suppressed emotion occurs</li>
              <li><strong>Unconscious Response:</strong> The mind perceives this as threatening</li>
              <li><strong>Physical Manifestation:</strong> The brain creates physical symptoms to distract attention</li>
              <li><strong>Fear Cycle:</strong> Fear of the symptoms reinforces and perpetuates them</li>
              <li><strong>Chronic Pattern:</strong> The cycle becomes self-sustaining</li>
            </ol>
            
            <h4>Common Mind-Body Symptoms</h4>
            <p>TMS can manifest in various ways:</p>
            <ul>
              <li><strong>Musculoskeletal:</strong> Back pain, neck pain, shoulder tension, fibromyalgia</li>
              <li><strong>Gastrointestinal:</strong> IBS, acid reflux, stomach pain</li>
              <li><strong>Neurological:</strong> Headaches, migraines, tingling, numbness</li>
              <li><strong>Other:</strong> Chronic fatigue, insomnia, anxiety, depression</li>
            </ul>
            
            <h4>Breaking the Cycle</h4>
            <p>Healing requires:</p>
            <ul>
              <li>Accepting that emotions can create physical symptoms</li>
              <li>Identifying and expressing suppressed emotions</li>
              <li>Reducing fear of the symptoms themselves</li>
              <li>Developing healthier coping mechanisms for stress</li>
              <li>Practicing self-compassion and emotional awareness</li>
            </ul>
          `,
        },
        {
          id: 'sarno-principles',
          title: "Dr. Sarno's Core Principles",
          preview:
            'The fundamental principles that guide TMS understanding and recovery',
          content: `
            <p>Dr. John Sarno developed specific principles that form the foundation of TMS theory and treatment. These principles have guided thousands to recovery.</p>
            
            <h4>Principle 1: The Pain is Real</h4>
            <p>Dr. Sarno always emphasized that TMS pain is genuine, not imaginary. The pain is created by real physiological processes—it's just that these processes are triggered by psychological factors rather than structural damage. This validation is crucial for healing.</p>
            
            <h4>Principle 2: Emotions Create Physical Symptoms</h4>
            <p>The unconscious mind can generate physical symptoms to serve as a distraction from uncomfortable emotions. This is not a conscious process—it happens automatically as a protective mechanism.</p>
            
            <h4>Principle 3: Knowledge is the Cure</h4>
            <p>Simply understanding that your pain is TMS-related can often begin the healing process. Many people experience immediate relief just from reading Dr. Sarno's books and recognizing themselves in the descriptions.</p>
            
            <h4>Principle 4: Focus on Emotions, Not Symptoms</h4>
            <p>Healing occurs when you shift attention from the physical symptoms to the underlying emotional issues. This includes:</p>
            <ul>
              <li>Identifying sources of stress and anger</li>
              <li>Recognizing perfectionist tendencies</li>
              <li>Acknowledging people-pleasing behaviors</li>
              <li>Processing past traumas or losses</li>
            </ul>
            
            <h4>Principle 5: Resume Normal Activities</h4>
            <p>Despite the pain, it's important to gradually return to normal physical activities. This demonstrates to your unconscious mind that you're not afraid of the symptoms and that there's no structural damage.</p>
            
            <h4>Principle 6: Reject the Physical Diagnosis</h4>
            <p>When appropriate (and with medical guidance), reject purely structural explanations for your pain. This doesn't mean ignoring serious medical conditions, but rather questioning whether minor structural findings truly explain your level of pain.</p>
            
            <h4>Principle 7: Address Psychological Factors</h4>
            <p>Successful recovery often involves:</p>
            <ul>
              <li>Therapy to process emotions and trauma</li>
              <li>Journaling to increase emotional awareness</li>
              <li>Stress reduction techniques</li>
              <li>Developing healthier relationship patterns</li>
              <li>Learning to express anger appropriately</li>
            </ul>
            
            <h4>Principle 8: Be Patient with the Process</h4>
            <p>Healing takes time and doesn't always follow a linear path. Some people experience immediate relief, while others need weeks or months to fully recover. Trust the process and be compassionate with yourself.</p>
          `,
        },
      ],
    },
    psychology: {
      title: 'Psychology of Pain',
      icon: '🧘',
      sections: [
        {
          id: 'emotional-repression',
          title: 'Understanding Emotional Repression',
          preview:
            'How suppressed emotions contribute to chronic pain and what to do about it',
          content: `
            <p>Emotional repression is one of the primary mechanisms behind TMS. Understanding this process is essential for recovery.</p>
            
            <h4>What is Emotional Repression?</h4>
            <p>Emotional repression occurs when we unconsciously push uncomfortable feelings out of our awareness. This is different from suppression (consciously choosing not to express emotions) or healthy emotional regulation.</p>
            
            <h4>Why We Repress Emotions</h4>
            <p>Repression often develops as a survival mechanism:</p>
            <ul>
              <li><strong>Childhood Protection:</strong> Children may repress emotions to maintain attachment to caregivers</li>
              <li><strong>Social Acceptance:</strong> Certain emotions (like anger) may be deemed unacceptable</li>
              <li><strong>Self-Image:</strong> Emotions that conflict with our self-concept get pushed away</li>
              <li><strong>Overwhelm:</strong> When emotions feel too intense, repression provides temporary relief</li>
            </ul>
            
            <h4>Common Repressed Emotions in TMS</h4>
            <ul>
              <li><strong>Rage:</strong> Often the most significant repressed emotion in TMS sufferers</li>
              <li><strong>Sadness:</strong> Grief, loss, disappointment that hasn't been processed</li>
              <li><strong>Fear:</strong> Anxiety about the future, fear of abandonment or failure</li>
              <li><strong>Shame:</strong> Deep feelings of inadequacy or worthlessness</li>
              <li><strong>Guilt:</strong> Self-blame and regret over past actions or thoughts</li>
            </ul>
            
            <h4>The Cost of Repression</h4>
            <p>When emotions are repressed, they don't disappear—they get stored in the body and unconscious mind, potentially manifesting as:</p>
            <ul>
              <li>Physical pain and tension</li>
              <li>Chronic illness symptoms</li>
              <li>Sleep disturbances</li>
              <li>Digestive issues</li>
              <li>Anxiety and depression</li>
            </ul>
            
            <h4>Signs You May Be Repressing Emotions</h4>
            <ul>
              <li>Difficulty identifying what you're feeling</li>
              <li>Saying you're "fine" when you're clearly not</li>
              <li>Physical symptoms that worsen during stress</li>
              <li>Perfectionist tendencies</li>
              <li>People-pleasing behaviors</li>
              <li>Avoiding conflict at all costs</li>
            </ul>
            
            <h4>Healing Through Emotional Awareness</h4>
            <p>Recovery involves learning to:</p>
            <ul>
              <li><strong>Recognize emotions</strong> as they arise</li>
              <li><strong>Name emotions</strong> specifically rather than using general terms</li>
              <li><strong>Feel emotions</strong> in your body without immediately acting on them</li>
              <li><strong>Express emotions</strong> appropriately and safely</li>
              <li><strong>Process emotions</strong> through journaling, therapy, or other means</li>
            </ul>
            
            <h4>Practical Steps for Emotional Awareness</h4>
            <ol>
              <li><strong>Daily Check-ins:</strong> Ask yourself "What am I feeling right now?"</li>
              <li><strong>Body Scanning:</strong> Notice where you feel tension or discomfort</li>
              <li><strong>Emotion Journaling:</strong> Write about your feelings without censoring</li>
              <li><strong>Mindfulness Practice:</strong> Observe emotions without judgment</li>
              <li><strong>Professional Support:</strong> Work with a therapist familiar with TMS</li>
            </ol>
          `,
        },
        {
          id: 'perfectionism',
          title: 'The Role of Perfectionism',
          preview:
            'How perfectionist tendencies contribute to TMS and strategies for healthy achievement',
          content: `
            <p>Perfectionism is one of the most common personality traits among TMS sufferers. Understanding and addressing perfectionist patterns is often crucial for healing.</p>
            
            <h4>Understanding Perfectionism in TMS</h4>
            <p>Perfectionism in TMS isn't just about wanting to do well—it's about setting impossibly high standards and being extremely self-critical when those standards aren't met. This creates enormous internal pressure and stress.</p>
            
            <h4>Types of Perfectionism</h4>
            <ul>
              <li><strong>Self-Oriented:</strong> Setting unrealistic standards for yourself</li>
              <li><strong>Other-Oriented:</strong> Expecting perfection from others</li>
              <li><strong>Socially Prescribed:</strong> Believing others expect perfection from you</li>
            </ul>
            
            <h4>How Perfectionism Creates TMS</h4>
            <p>Perfectionism contributes to TMS through several mechanisms:</p>
            <ul>
              <li><strong>Chronic Stress:</strong> Constant pressure to be perfect creates ongoing stress</li>
              <li><strong>Repressed Anger:</strong> Anger at not meeting impossible standards gets pushed down</li>
              <li><strong>Self-Criticism:</strong> Harsh internal dialogue creates emotional pain</li>
              <li><strong>Fear of Failure:</strong> Anxiety about not being good enough</li>
              <li><strong>Control Issues:</strong> Need to control outcomes creates tension when life is unpredictable</li>
            </ul>
            
            <h4>Signs of Perfectionism</h4>
            <ul>
              <li>All-or-nothing thinking</li>
              <li>Procrastination due to fear of imperfection</li>
              <li>Difficulty delegating tasks</li>
              <li>Overworking or overachieving</li>
              <li>Harsh self-criticism</li>
              <li>Difficulty accepting compliments</li>
              <li>Fear of making mistakes</li>
              <li>Comparing yourself constantly to others</li>
            </ul>
            
            <h4>The Hidden Costs of Perfectionism</h4>
            <ul>
              <li>Chronic stress and anxiety</li>
              <li>Burnout and exhaustion</li>
              <li>Relationship difficulties</li>
              <li>Decreased creativity and innovation</li>
              <li>Reduced life satisfaction</li>
              <li>Physical symptoms including pain</li>
            </ul>
            
            <h4>Transforming Perfectionism</h4>
            <p>Healing doesn't mean becoming mediocre—it means developing healthy striving instead of perfectionism:</p>
            
            <h5>Healthy Striving vs. Perfectionism</h5>
            <table style="width: 100%; border-collapse: collapse; margin: 16px 0;">
              <tr style="background-color: #f3f4f6;">
                <th style="padding: 8px; text-align: left; border: 1px solid #e5e7eb;">Perfectionism</th>
                <th style="padding: 8px; text-align: left; border: 1px solid #e5e7eb;">Healthy Striving</th>
              </tr>
              <tr>
                <td style="padding: 8px; border: 1px solid #e5e7eb;">All-or-nothing standards</td>
                <td style="padding: 8px; border: 1px solid #e5e7eb;">High but achievable standards</td>
              </tr>
              <tr>
                <td style="padding: 8px; border: 1px solid #e5e7eb;">Focus on outcome only</td>
                <td style="padding: 8px; border: 1px solid #e5e7eb;">Focus on process and growth</td>
              </tr>
              <tr>
                <td style="padding: 8px; border: 1px solid #e5e7eb;">Mistakes are failures</td>
                <td style="padding: 8px; border: 1px solid #e5e7eb;">Mistakes are learning opportunities</td>
              </tr>
              <tr>
                <td style="padding: 8px; border: 1px solid #e5e7eb;">Self-worth tied to achievement</td>
                <td style="padding: 8px; border: 1px solid #e5e7eb;">Self-worth is inherent</td>
              </tr>
            </table>
            
            <h4>Practical Strategies for Overcoming Perfectionism</h4>
            <ol>
              <li><strong>Practice "Good Enough":</strong> Deliberately do some things at 80% instead of 100%</li>
              <li><strong>Set Time Limits:</strong> Give yourself deadlines to prevent endless tweaking</li>
              <li><strong>Embrace Mistakes:</strong> Intentionally make small mistakes to reduce fear</li>
              <li><strong>Challenge All-or-Nothing Thinking:</strong> Look for middle ground and nuance</li>
              <li><strong>Practice Self-Compassion:</strong> Treat yourself as you would a good friend</li>
              <li><strong>Focus on Progress:</strong> Celebrate improvement rather than just end results</li>
              <li><strong>Delegate and Ask for Help:</strong> You don't have to do everything yourself</li>
            </ol>
          `,
        },
        {
          id: 'people-pleasing',
          title: 'People-Pleasing and Boundary Issues',
          preview:
            'How the need to please others contributes to internal conflict and physical symptoms',
          content: `
            <p>People-pleasing is another common trait among TMS sufferers. The constant need to keep others happy while ignoring your own needs creates significant internal conflict that can manifest as physical symptoms.</p>
            
            <h4>Understanding People-Pleasing</h4>
            <p>People-pleasing goes beyond being kind or considerate. It's a compulsive need to gain approval and avoid conflict, often at the expense of your own well-being. This pattern typically develops early in life as a survival strategy.</p>
            
            <h4>How People-Pleasing Develops</h4>
            <ul>
              <li><strong>Childhood Conditioning:</strong> Learning that love and acceptance are conditional on being "good"</li>
              <li><strong>Trauma Response:</strong> Avoiding conflict to prevent emotional or physical harm</li>
              <li><strong>Low Self-Worth:</strong> Believing you're only valuable when you're useful to others</li>
              <li><strong>Fear of Abandonment:</strong> Terror of being rejected or left alone</li>
            </ul>
            
            <h4>Signs of People-Pleasing</h4>
            <ul>
              <li>Difficulty saying "no" even when overwhelmed</li>
              <li>Apologizing excessively</li>
              <li>Agreeing with others even when you disagree</li>
              <li>Taking responsibility for others' emotions</li>
              <li>Avoiding conflict at all costs</li>
              <li>Feeling guilty when you prioritize your needs</li>
              <li>Seeking constant validation and approval</li>
              <li>Feeling resentful but not expressing it</li>
            </ul>
            
            <h4>The TMS Connection</h4>
            <p>People-pleasing creates TMS through several mechanisms:</p>
            <ul>
              <li><strong>Repressed Anger:</strong> Constant self-sacrifice builds hidden resentment</li>
              <li><strong>Internal Conflict:</strong> The war between your needs and others' expectations</li>
              <li><strong>Chronic Stress:</strong> Always being "on" and available for others</li>
              <li><strong>Loss of Self:</strong> Not knowing what you actually want or need</li>
              <li><strong>Emotional Exhaustion:</strong> Giving constantly without receiving</li>
            </ul>
            
            <h4>The Cost of People-Pleasing</h4>
            <ul>
              <li>Chronic fatigue and burnout</li>
              <li>Resentment and suppressed anger</li>
              <li>Loss of authentic self</li>
              <li>Unhealthy relationships</li>
              <li>Physical symptoms including pain</li>
              <li>Anxiety and depression</li>
            </ul>
            
            <h4>Healthy Boundaries</h4>
            <p>Recovery involves learning to set and maintain healthy boundaries:</p>
            
            <h5>Types of Boundaries</h5>
            <ul>
              <li><strong>Physical:</strong> Your body, personal space, privacy</li>
              <li><strong>Emotional:</strong> Your feelings, thoughts, values</li>
              <li><strong>Time:</strong> How you spend your time and energy</li>
              <li><strong>Mental:</strong> Your beliefs, opinions, decisions</li>
              <li><strong>Material:</strong> Your possessions, money, resources</li>
            </ul>
            
            <h4>Steps to Overcome People-Pleasing</h4>
            <ol>
              <li><strong>Recognize the Pattern:</strong> Become aware of when you're people-pleasing</li>
              <li><strong>Identify Your Needs:</strong> Learn to recognize what you actually want</li>
              <li><strong>Start Small:</strong> Practice saying "no" to small requests</li>
              <li><strong>Use "I" Statements:</strong> Express your needs clearly and directly</li>
              <li><strong>Accept Discomfort:</strong> Others may not like your boundaries initially</li>
              <li><strong>Build Self-Worth:</strong> Work on valuing yourself independent of others' approval</li>
              <li><strong>Practice Self-Care:</strong> Prioritize your own well-being</li>
            </ol>
            
            <h4>Boundary Scripts</h4>
            <p>Practice these phrases to help set boundaries:</p>
            <ul>
              <li>"I need to think about that before I commit."</li>
              <li>"That doesn't work for me."</li>
              <li>"I'm not comfortable with that."</li>
              <li>"I understand you're disappointed, but this is what I need."</li>
              <li>"I'd love to help, but I can't right now."</li>
            </ul>
            
            <h4>Remember</h4>
            <p>Setting boundaries isn't selfish—it's necessary for your health and actually improves your relationships. When you take care of yourself, you can show up more authentically and generously for others.</p>
          `,
        },
      ],
    },
    healing: {
      title: 'Healing Strategies',
      icon: '🌱',
      sections: [
        {
          id: 'journaling-techniques',
          title: 'Therapeutic Journaling',
          preview:
            'Powerful journaling techniques specifically designed for TMS recovery',
          content: `
            <p>Journaling is one of the most powerful tools for TMS recovery. It helps you connect with repressed emotions, identify patterns, and process difficult experiences.</p>
            
            <h4>Why Journaling Works for TMS</h4>
            <ul>
              <li><strong>Emotional Access:</strong> Writing bypasses mental defenses and accesses deeper emotions</li>
              <li><strong>Pattern Recognition:</strong> Helps identify triggers and connections between emotions and symptoms</li>
              <li><strong>Stress Release:</strong> Provides a safe outlet for difficult feelings</li>
              <li><strong>Self-Understanding:</strong> Increases awareness of your inner world</li>
              <li><strong>Healing Processing:</strong> Helps process trauma and difficult experiences</li>
            </ul>
            
            <h4>Types of TMS Journaling</h4>
            
            <h5>1. Free-Writing (Stream of Consciousness)</h5>
            <p>Write continuously for 10-20 minutes without stopping, editing, or censoring. Let whatever comes up flow onto the page.</p>
            <ul>
              <li>Don't worry about grammar or spelling</li>
              <li>If you get stuck, write "I don't know what to write" until something comes</li>
              <li>This technique often reveals unconscious thoughts and feelings</li>
            </ul>
            
            <h5>2. Emotional Processing</h5>
            <p>Focus specifically on exploring emotions:</p>
            <ul>
              <li>"What am I feeling right now?"</li>
              <li>"What am I angry about?"</li>
              <li>"What am I sad about?"</li>
              <li>"What am I afraid of?"</li>
              <li>"What do I need that I'm not getting?"</li>
            </ul>
            
            <h5>3. Dialogue Writing</h5>
            <p>Have conversations on paper with different parts of yourself:</p>
            <ul>
              <li>Your inner critic vs. your compassionate self</li>
              <li>Your adult self vs. your inner child</li>
              <li>Your conscious mind vs. your unconscious mind</li>
              <li>Yourself vs. your symptoms</li>
            </ul>
            
            <h5>4. Letter Writing</h5>
            <p>Write letters you'll never send to:</p>
            <ul>
              <li>People who have hurt you</li>
              <li>Yourself at different ages</li>
              <li>Your symptoms or illness</li>
              <li>Deceased loved ones</li>
            </ul>
            
            <h4>Specific TMS Journaling Prompts</h4>
            
            <h5>Anger Exploration</h5>
            <ul>
              <li>"What am I angry about that I haven't acknowledged?"</li>
              <li>"Who am I angry at and why?"</li>
              <li>"What would I say if I could express my anger freely?"</li>
              <li>"How was anger handled in my family growing up?"</li>
            </ul>
            
            <h5>Perfectionism and Pressure</h5>
            <ul>
              <li>"What pressures am I putting on myself?"</li>
              <li>"Where do these expectations come from?"</li>
              <li>"What would happen if I wasn't perfect?"</li>
              <li>"How do I treat myself when I make mistakes?"</li>
            </ul>
            
            <h5>Relationship Patterns</h5>
            <ul>
              <li>"How do I sacrifice myself for others?"</li>
              <li>"What do I need in my relationships that I'm not asking for?"</li>
              <li>"Where do I feel resentful and why?"</li>
              <li>"How do I avoid conflict and what does this cost me?"</li>
            </ul>
            
            <h4>Advanced Techniques</h4>
            
            <h5>The Unsent Letter Technique</h5>
            <ol>
              <li>Write a completely honest letter to someone (living or dead)</li>
              <li>Express everything you've never said</li>
              <li>Don't censor yourself—this is for you only</li>
              <li>When finished, you can burn, bury, or keep the letter</li>
              <li>Notice how your body feels before and after</li>
            </ol>
            
            <h5>Timeline Journaling</h5>
            <ol>
              <li>Create a timeline of your life's major stressors</li>
              <li>Note when your symptoms began or worsened</li>
              <li>Look for patterns and connections</li>
              <li>Write about each significant event and its emotional impact</li>
            </ol>
            
            <h4>Journaling Guidelines</h4>
            <ul>
              <li><strong>Consistency:</strong> Aim for daily practice, even if just 5-10 minutes</li>
              <li><strong>Privacy:</strong> Keep your journal completely private to encourage honesty</li>
              <li><strong>No Judgment:</strong> Write without censoring or judging yourself</li>
              <li><strong>Feel Your Feelings:</strong> Allow emotions to arise as you write</li>
              <li><strong>Physical Awareness:</strong> Notice how your body responds to what you write</li>
            </ul>
            
            <h4>What to Expect</h4>
            <ul>
              <li>Initial resistance or feeling like you have "nothing to write"</li>
              <li>Surprising emotions or memories surfacing</li>
              <li>Temporary increase in symptoms as emotions are processed</li>
              <li>Gradual increase in emotional awareness and symptom relief</li>
              <li>Greater clarity about your patterns and triggers</li>
            </ul>
            
            <h4>When Journaling Brings Up Difficult Material</h4>
            <p>If journaling triggers intense emotions or memories:</p>
            <ul>
              <li>This is often a sign the process is working</li>
              <li>Take breaks if needed</li>
              <li>Consider working with a TMS-informed therapist</li>
              <li>Practice self-care and self-compassion</li>
              <li>Remember that feeling emotions won't harm you</li>
            </ul>
          `,
        },
        {
          id: 'emotional-regulation',
          title: 'Emotional Regulation Techniques',
          preview:
            'Learn healthy ways to experience, process, and express emotions',
          content: `
            <p>Learning to regulate emotions healthily is crucial for TMS recovery. This doesn't mean suppressing emotions, but rather developing a healthy relationship with your emotional life.</p>
            
            <h4>Understanding Emotional Regulation</h4>
            <p>Emotional regulation is the ability to:</p>
            <ul>
              <li>Recognize emotions as they arise</li>
              <li>Tolerate difficult emotions without being overwhelmed</li>
              <li>Express emotions appropriately</li>
              <li>Use emotions as information about your needs</li>
              <li>Return to emotional balance after being triggered</li>
            </ul>
            
            <h4>The Window of Tolerance</h4>
            <p>Your "window of tolerance" is the zone where you can handle stress and emotions without becoming overwhelmed or shutting down. TMS recovery involves expanding this window.</p>
            
            <h5>Signs You're Outside Your Window:</h5>
            <ul>
              <li><strong>Hyperarousal:</strong> Anxiety, panic, rage, hypervigilance</li>
              <li><strong>Hypoarousal:</strong> Numbness, disconnection, depression, brain fog</li>
            </ul>
            
            <h4>Techniques for Emotional Regulation</h4>
            
            <h5>1. Mindful Emotion Awareness</h5>
            <p>Practice observing emotions without immediately reacting:</p>
            <ol>
              <li>Notice the emotion arising</li>
              <li>Name it: "I'm feeling angry" or "This is sadness"</li>
              <li>Locate it in your body</li>
              <li>Breathe and allow it to be present</li>
              <li>Ask: "What is this emotion telling me?"</li>
            </ol>
            
            <h5>2. The STOP Technique</h5>
            <p>When overwhelmed by emotions:</p>
            <ul>
              <li><strong>S</strong> - Stop what you're doing</li>
              <li><strong>T</strong> - Take a breath (or several deep breaths)</li>
              <li><strong>O</strong> - Observe what's happening in your body and mind</li>
              <li><strong>P</strong> - Proceed with awareness and intention</li>
            </ul>
            
            <h5>3. Grounding Techniques</h5>
            <p>When emotions feel overwhelming, grounding brings you back to the present:</p>
            <ul>
              <li><strong>5-4-3-2-1 Technique:</strong> Name 5 things you see, 4 you can touch, 3 you hear, 2 you smell, 1 you taste</li>
              <li><strong>Cold Water:</strong> Splash cold water on your face or hold ice cubes</li>
              <li><strong>Progressive Muscle Relaxation:</strong> Tense and release muscle groups</li>
              <li><strong>Box Breathing:</strong> Inhale for 4, hold for 4, exhale for 4, hold for 4</li>
            </ul>
            
            <h5>4. Emotional Expression Techniques</h5>
            <p>Healthy ways to express difficult emotions:</p>
            <ul>
              <li><strong>Physical Movement:</strong> Walking, dancing, exercise to move energy</li>
              <li><strong>Vocal Expression:</strong> Screaming into a pillow, singing, humming</li>
              <li><strong>Creative Expression:</strong> Drawing, painting, music, poetry</li>
              <li><strong>Writing:</strong> Journaling, letters, stream of consciousness</li>
              <li><strong>Safe Anger Release:</strong> Hitting pillows, squeezing stress balls</li>
            </ul>
            
            <h4>Working with Specific Emotions</h4>
            
            <h5>Anger</h5>
            <p>Anger is often the most repressed emotion in TMS:</p>
            <ul>
              <li><strong>Recognize:</strong> Tension, heat, clenched jaw, tight fists</li>
              <li><strong>Validate:</strong> Anger is a normal response to feeling hurt or violated</li>
              <li><strong>Express Safely:</strong> Physical exercise, journaling, talking to trusted friend</li>
              <li><strong>Set Boundaries:</strong> Use anger's energy to protect yourself</li>
            </ul>
            <h5>Sadness</h5>
            <p>Sadness helps us process loss and disappointment:</p>
            <ul>
              <li><strong>Allow Tears:</strong> Crying is a natural and healing response</li>
              <li><strong>Seek Comfort:</strong> Reach out for support when needed</li>
              <li><strong>Honor Losses:</strong> Acknowledge what you're grieving</li>
              <li><strong>Be Patient:</strong> Sadness has its own timeline</li>
            </ul>
            
            <h5>Fear and Anxiety</h5>
            <p>Fear alerts us to potential threats:</p>
            <ul>
              <li><strong>Distinguish:</strong> Real danger vs. anxious thoughts</li>
              <li><strong>Breathe:</strong> Slow, deep breathing calms the nervous system</li>
              <li><strong>Ground Yourself:</strong> Focus on present moment reality</li>
              <li><strong>Take Action:</strong> Address real concerns when possible</li>
            </ul>
            
            <h4>Building Emotional Resilience</h4>
            
            <h5>Daily Practices</h5>
            <ul>
              <li><strong>Emotion Check-ins:</strong> Ask yourself how you're feeling several times a day</li>
              <li><strong>Body Scanning:</strong> Notice where emotions show up physically</li>
              <li><strong>Feeling Journaling:</strong> Write about emotions without trying to fix them</li>
              <li><strong>Self-Compassion:</strong> Treat yourself kindly during difficult emotions</li>
            </ul>
            
            <h5>Building Your Support System</h5>
            <ul>
              <li>Identify trusted people you can share emotions with</li>
              <li>Consider therapy, especially with TMS-informed practitioners</li>
              <li>Join support groups for people with chronic pain or TMS</li>
              <li>Practice asking for help when you need it</li>
            </ul>
            
            <h4>Common Emotional Regulation Mistakes</h4>
            <ul>
              <li><strong>Trying to "positive think" away negative emotions</strong></li>
              <li><strong>Judging emotions as "good" or "bad"</strong></li>
              <li><strong>Trying to control or change emotions immediately</strong></li>
              <li><strong>Avoiding situations that might trigger emotions</strong></li>
              <li><strong>Using substances or behaviors to numb emotions</strong></li>
            </ul>
            
            <h4>Signs of Improving Emotional Regulation</h4>
            <ul>
              <li>Faster recovery from emotional triggers</li>
              <li>Increased emotional vocabulary</li>
              <li>Better relationships and communication</li>
              <li>Reduced physical symptoms</li>
              <li>Greater sense of inner calm and stability</li>
              <li>Ability to be present with others' emotions</li>
            </ul>
            
            <h4>Remember</h4>
            <p>Developing emotional regulation skills takes time and practice. Be patient with yourself as you learn. Every time you choose to feel and process an emotion rather than suppress it, you're supporting your healing journey.</p>
          `,
        },
        {
          id: 'stress-management',
          title: 'Stress Management & Self-Care',
          preview:
            'Comprehensive strategies for managing stress and caring for yourself during recovery',
          content: `
            <p>Stress management is crucial for TMS recovery because chronic stress perpetuates the mind-body pain cycle. Learning to manage stress effectively helps break this cycle and supports healing.</p>
            
            <h4>Understanding Stress and TMS</h4>
            <p>Stress affects TMS through multiple pathways:</p>
            <ul>
              <li><strong>Physical:</strong> Muscle tension, inflammation, immune system suppression</li>
              <li><strong>Emotional:</strong> Increased anxiety, depression, emotional reactivity</li>
              <li><strong>Mental:</strong> Racing thoughts, difficulty concentrating, catastrophic thinking</li>
              <li><strong>Behavioral:</strong> Sleep disruption, poor eating habits, social isolation</li>
            </ul>
            
            <h4>Types of Stress in TMS</h4>
            
            <h5>Acute Stress</h5>
            <p>Short-term stress from specific events:</p>
            <ul>
              <li>Work deadlines or conflicts</li>
              <li>Relationship issues</li>
              <li>Financial concerns</li>
              <li>Health scares</li>
            </ul>
            
            <h5>Chronic Stress</h5>
            <p>Long-term, ongoing stress that's often more damaging:</p>
            <ul>
              <li>Perfectionist self-imposed pressure</li>
              <li>Difficult relationships or family dynamics</li>
              <li>Work dissatisfaction or overload</li>
              <li>Financial insecurity</li>
              <li>Caregiving responsibilities</li>
            </ul>
            
            <h5>Internal Stress</h5>
            <p>Stress created by your own thoughts and patterns:</p>
            <ul>
              <li>Self-criticism and negative self-talk</li>
              <li>Perfectionist expectations</li>
              <li>Catastrophic thinking</li>
              <li>Rumination and worry</li>
            </ul>
            <h4>Comprehensive Stress Management Strategies</h4>
            
            <h5>1. Immediate Stress Relief Techniques</h5>
            <p>For when you're feeling overwhelmed in the moment:</p>
            <ul>
              <li><strong>Deep Breathing:</strong> 4-7-8 breathing (inhale 4, hold 7, exhale 8)</li>
              <li><strong>Progressive Muscle Relaxation:</strong> Tense and release muscle groups</li>
              <li><strong>Cold Water:</strong> Splash on face or drink slowly</li>
              <li><strong>Movement:</strong> Walk, stretch, or do jumping jacks</li>
              <li><strong>Grounding:</strong> Focus on your five senses</li>
            </ul>
            
            <h5>2. Daily Stress Management Practices</h5>
            
            <h6>Mindfulness and Meditation</h6>
            <ul>
              <li><strong>Mindful Breathing:</strong> 10-20 minutes daily focused breathing</li>
              <li><strong>Body Scan Meditation:</strong> Systematic relaxation of body parts</li>
              <li><strong>Mindful Walking:</strong> Focused attention while walking</li>
              <li><strong>Loving-Kindness Meditation:</strong> Cultivating compassion for self and others</li>
            </ul>
            
            <h6>Physical Stress Relief</h6>
            <ul>
              <li><strong>Regular Exercise:</strong> Even 20-30 minutes daily helps</li>
              <li><strong>Yoga:</strong> Combines movement, breathing, and mindfulness</li>
              <li><strong>Stretching:</strong> Releases physical tension</li>
              <li><strong>Massage:</strong> Professional or self-massage</li>
              <li><strong>Hot Baths:</strong> Warm water relaxes muscles and mind</li>
            </ul>
            
            <h6>Mental Stress Relief</h6>
            <ul>
              <li><strong>Cognitive Restructuring:</strong> Challenge negative thought patterns</li>
              <li><strong>Worry Time:</strong> Designate 15 minutes daily for worrying, then stop</li>
              <li><strong>Gratitude Practice:</strong> Daily appreciation exercises</li>
              <li><strong>Mental Boundaries:</strong> Learn to say no to mental overload</li>
            </ul>
            
            <h4>Self-Care Fundamentals</h4>
            
            <h5>Physical Self-Care</h5>
            <ul>
              <li><strong>Sleep Hygiene:</strong> 7-9 hours of quality sleep</li>
              <li><strong>Nutrition:</strong> Regular, balanced meals</li>
              <li><strong>Hydration:</strong> Adequate water intake</li>
              <li><strong>Movement:</strong> Regular physical activity you enjoy</li>
              <li><strong>Medical Care:</strong> Regular check-ups and preventive care</li>
            </ul>
            
            <h5>Emotional Self-Care</h5>
            <ul>
              <li><strong>Emotional Expression:</strong> Regular outlets for feelings</li>
              <li><strong>Therapy:</strong> Professional emotional support</li>
              <li><strong>Journaling:</strong> Processing thoughts and feelings</li>
              <li><strong>Creative Expression:</strong> Art, music, writing</li>
              <li><strong>Emotional Boundaries:</strong> Protecting your emotional energy</li>
            </ul>
            
            <h5>Social Self-Care</h5>
            <ul>
              <li><strong>Quality Relationships:</strong> Nurture supportive connections</li>
              <li><strong>Social Boundaries:</strong> Limit toxic relationships</li>
              <li><strong>Community:</strong> Engage in meaningful groups or activities</li>
              <li><strong>Communication:</strong> Express needs and feelings clearly</li>
              <li><strong>Alone Time:</strong> Balance social time with solitude</li>
            </ul>
            
            <h5>Spiritual Self-Care</h5>
            <ul>
              <li><strong>Meaning and Purpose:</strong> Connect with what matters to you</li>
              <li><strong>Nature Connection:</strong> Spend time outdoors</li>
              <li><strong>Meditation or Prayer:</strong> Spiritual practices</li>
              <li><strong>Values Alignment:</strong> Live according to your values</li>
              <li><strong>Service:</strong> Help others in meaningful ways</li>
            </ul>
            
            <h4>Lifestyle Changes for Stress Reduction</h4>
            
            <h5>Time Management</h5>
            <ul>
              <li><strong>Prioritization:</strong> Focus on what truly matters</li>
              <li><strong>Delegation:</strong> Ask for help when possible</li>
              <li><strong>Time Boundaries:</strong> Protect your time and energy</li>
              <li><strong>Realistic Scheduling:</strong> Don't overpack your calendar</li>
            </ul>
            
            <h5>Environment</h5>
            <ul>
              <li><strong>Organize Spaces:</strong> Reduce clutter and chaos</li>
              <li><strong>Create Calm Spaces:</strong> Designate areas for relaxation</li>
              <li><strong>Limit News/Social Media:</strong> Reduce information overload</li>
              <li><strong>Nature Access:</strong> Spend time in natural settings</li>
            </ul>
            
            <h4>Building Stress Resilience</h4>
            
            <h5>Developing Coping Skills</h5>
            <ul>
              <li><strong>Problem-Solving:</strong> Break big problems into manageable steps</li>
              <li><strong>Flexibility:</strong> Practice adapting to change</li>
              <li><strong>Perspective:</strong> Look for learning opportunities in challenges</li>
              <li><strong>Humor:</strong> Find lightness even in difficult situations</li>
            </ul>
            
            <h5>Building Support Systems</h5>
            <ul>
              <li><strong>Professional Support:</strong> Therapists, coaches, medical team</li>
              <li><strong>Personal Support:</strong> Family, friends, chosen family</li>
              <li><strong>Community Support:</strong> Groups, organizations, spiritual communities</li>
              <li><strong>Peer Support:</strong> Others with similar experiences</li>
            </ul>
            
            <h4>Creating Your Personal Stress Management Plan</h4>
            <ol>
              <li><strong>Identify Your Stressors:</strong> What specific things cause you stress?</li>
              <li><strong>Recognize Your Stress Signals:</strong> How does stress show up in your body and mind?</li>
              <li><strong>Choose Your Tools:</strong> Select 3-5 stress management techniques that appeal to you</li>
              <li><strong>Create Routines:</strong> Build stress management into your daily schedule</li>
              <li><strong>Plan for Crisis:</strong> Have specific strategies for high-stress times</li>
              <li><strong>Regular Review:</strong> Assess what's working and adjust as needed</li>
            </ol>
            
            <h4>Remember</h4>
            <p>Stress management is a skill that improves with practice. Start small and be consistent. Even five minutes of stress relief daily can make a significant difference in your overall well-being and TMS recovery.</p>
          `,
        },
      ],
    },
    recovery: {
      title: 'Recovery Stories',
      icon: '🌟',
      sections: [
        {
          id: 'recovery-principles',
          title: 'Principles of TMS Recovery',
          preview: 'Core principles that guide successful healing from TMS',
          content: `
            <p>Recovery from TMS follows certain principles that have been observed across thousands of successful cases. Understanding these principles can guide your own healing journey.</p>
            
            <h4>The Foundation of Recovery</h4>
            <p>TMS recovery is built on a fundamental shift in understanding: moving from a purely biomedical model of pain to a biopsychosocial model that recognizes the powerful role of emotions and stress in creating physical symptoms.</p>
            
            <h4>Core Recovery Principles</h4>
            
            <h5>1. Knowledge and Understanding</h5>
            <p>Education is often the first step toward healing:</p>
            <ul>
              <li><strong>Learn the Science:</strong> Understand how emotions create physical symptoms</li>
              <li><strong>Recognize Patterns:</strong> See how your personality traits contribute to TMS</li>
              <li><strong>Question Structural Diagnoses:</strong> Consider whether minor findings truly explain your pain level</li>
              <li><strong>Read Success Stories:</strong> Learn from others who have healed</li>
            </ul>
            
            <h5>2. Emotional Awareness and Processing</h5>
            <p>Healing requires reconnecting with your emotional life:</p>
            <ul>
              <li><strong>Identify Repressed Emotions:</strong> Especially anger, sadness, and fear</li>
              <li><strong>Feel Without Fear:</strong> Learn that emotions won't harm you</li>
              <li><strong>Express Appropriately:</strong> Find healthy outlets for difficult feelings</li>
              <li><strong>Process Past Trauma:</strong> Work through unresolved experiences</li>
            </ul>
            
            <h5>3. Addressing Psychological Patterns</h5>
            <p>Recovery often requires changing ingrained patterns:</p>
            <ul>
              <li><strong>Perfectionism:</strong> Develop healthy striving instead of impossible standards</li>
              <li><strong>People-Pleasing:</strong> Learn to set boundaries and prioritize your needs</li>
              <li><strong>Control Issues:</strong> Accept uncertainty and practice letting go</li>
              <li><strong>Self-Criticism:</strong> Develop self-compassion and kindness</li>
            </ul>
            <h5>4. Fear Reduction</h5>
            <p>Fear often perpetuates TMS symptoms:</p>
            <ul>
              <li><strong>Fear of Movement:</strong> Gradually resume normal activities</li>
              <li><strong>Fear of Pain:</strong> Change your relationship with symptoms</li>
              <li><strong>Fear of Emotions:</strong> Learn to welcome all feelings</li>
              <li><strong>Fear of the Future:</strong> Focus on present moment healing</li>
            </ul>
            
            <h5>5. Lifestyle Changes</h5>
            <p>Supporting recovery through daily choices:</p>
            <ul>
              <li><strong>Stress Management:</strong> Develop effective stress reduction techniques</li>
              <li><strong>Self-Care:</strong> Prioritize your physical and emotional well-being</li>
              <li><strong>Relationships:</strong> Improve communication and boundary-setting</li>
              <li><strong>Work-Life Balance:</strong> Create sustainable patterns</li>
            </ul>
            
            <h4>Stages of Recovery</h4>
            
            <h5>Stage 1: Recognition and Education (Weeks 1-4)</h5>
            <ul>
              <li>Learning about TMS and recognizing yourself in the descriptions</li>
              <li>Beginning to question purely structural explanations</li>
              <li>Starting to notice emotional and stress patterns</li>
              <li>Reading books and educational materials</li>
              <li>Some people experience immediate improvement at this stage</li>
            </ul>
            
            <h5>Stage 2: Emotional Exploration (Months 1-6)</h5>
            <ul>
              <li>Beginning journaling and emotional awareness practices</li>
              <li>Identifying repressed emotions and psychological patterns</li>
              <li>Working with therapy or other emotional support</li>
              <li>Symptoms may fluctuate as emotions are processed</li>
              <li>Gradual increase in activity levels</li>
            </ul>
            
            <h5>Stage 3: Integration and Practice (Months 3-12)</h5>
            <ul>
              <li>Developing new emotional and behavioral patterns</li>
              <li>Consistent practice of stress management and self-care</li>
              <li>Continued work on perfectionism and people-pleasing</li>
              <li>Building resilience and emotional regulation skills</li>
              <li>Significant symptom improvement for most people</li>
            </ul>
            
            <h5>Stage 4: Maintenance and Growth (Ongoing)</h5>
            <ul>
              <li>Maintaining emotional awareness and healthy patterns</li>
              <li>Continuing personal growth and self-development</li>
              <li>Helping others who are beginning their healing journey</li>
              <li>Living with confidence in your body's health</li>
              <li>Using setbacks as opportunities for deeper healing</li>
            </ul>
            
            <h4>Common Recovery Patterns</h4>
            
            <h5>The "Book Cure"</h5>
            <p>Some people (about 10-20%) experience dramatic improvement just from reading about TMS and recognizing their patterns. This typically happens to people who:</p>
            <ul>
              <li>Have strong intellectual understanding</li>
              <li>Are ready to accept the mind-body connection</li>
              <li>Have less complex trauma histories</li>
              <li>Are able to quickly reduce fear of their symptoms</li>
            </ul>
            
            <h5>The Gradual Recovery</h5>
            <p>Most people (60-70%) experience gradual improvement over 3-12 months:</p>
            <ul>
              <li>Symptoms slowly decrease in intensity and frequency</li>
              <li>Good days become more frequent</li>
              <li>Setbacks become shorter and less severe</li>
              <li>Emotional awareness and coping skills develop progressively</li>
            </ul>
            
            <h5>The Complex Recovery</h5>
            <p>Some people (10-20%) need longer or more intensive work:</p>
            <ul>
              <li>May have complex trauma histories</li>
              <li>Might need extensive therapy and emotional processing</li>
              <li>Could have multiple or very severe symptoms</li>
              <li>Recovery may take 1-2 years or longer</li>
            </ul>
            
            <h4>Factors That Support Recovery</h4>
            
            <h5>Internal Factors</h5>
            <ul>
              <li><strong>Openness to the mind-body connection</strong></li>
              <li><strong>Willingness to feel and process emotions</strong></li>
              <li><strong>Commitment to personal growth and change</strong></li>
              <li><strong>Patience with the healing process</strong></li>
              <li><strong>Self-compassion during setbacks</strong></li>
            </ul>
            
            <h5>External Factors</h5>
            <ul>
              <li><strong>Supportive relationships and community</strong></li>
              <li><strong>Access to TMS-informed healthcare providers</strong></li>
              <li><strong>Reduced external stressors when possible</strong></li>
              <li><strong>Time and space for self-care and healing work</strong></li>
              <li><strong>Financial and practical support for treatment</strong></li>
            </ul>
            
            <h4>Remember</h4>
            <p>Recovery is possible for most people with TMS. While the journey may have challenges, thousands of people have healed using these principles. Trust in your body's ability to heal and be patient with the process.</p>
          `,
        },
      ],
    },
  };

  const ExpandableSection = ({ section, isExpanded, onToggle }) => (
    <div
      style={{
        backgroundColor: 'white',
        borderRadius: '12px',
        boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
        marginBottom: '16px',
        border: '1px solid #e5e7eb',
      }}
    >
      <button
        onClick={onToggle}
        style={{
          width: '100%',
          padding: '20px',
          border: 'none',
          background: 'none',
          textAlign: 'left',
          cursor: 'pointer',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
        }}
      >
        <div>
          <h3
            style={{
              fontSize: '18px',
              fontWeight: '600',
              color: '#1f2937',
              margin: '0 0 8px 0',
            }}
          >
            {section.title}
          </h3>
          <p
            style={{
              fontSize: '14px',
              color: '#6b7280',
              margin: 0,
              lineHeight: '1.5',
            }}
          >
            {section.preview}
          </p>
        </div>
        <div
          style={{
            fontSize: '20px',
            color: '#6b7280',
            transform: isExpanded ? 'rotate(180deg)' : 'rotate(0deg)',
            transition: 'transform 0.2s ease',
          }}
        >
          ▼
        </div>
      </button>

      {isExpanded && (
        <div
          style={{
            padding: '0 20px 20px 20px',
            borderTop: '1px solid #f3f4f6',
            marginTop: '16px',
          }}
        >
          <div
            style={{
              fontSize: '14px',
              color: '#374151',
              lineHeight: '1.7',
            }}
            dangerouslySetInnerHTML={{ __html: section.content }}
          />
        </div>
      )}
    </div>
  );

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      <div style={{ textAlign: 'center', marginBottom: '24px' }}>
        <h2
          style={{
            fontSize: '28px',
            fontWeight: 'bold',
            color: '#1f2937',
            marginBottom: '8px',
          }}
        >
          TMS Learning Center
        </h2>
        <p style={{ color: '#6b7280' }}>
          Comprehensive education on mind-body healing and TMS recovery
        </p>
      </div>

      {/* Tab Navigation */}
      <div
        style={{
          display: 'flex',
          justifyContent: 'center',
          flexWrap: 'wrap',
          gap: '8px',
          marginBottom: '32px',
        }}
      >
        {Object.entries(educationalTabs).map(([key, tab]) => (
          <button
            key={key}
            onClick={() => {
              setActiveTab(key);
              setExpandedSection(null);
            }}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '8px',
              padding: '12px 20px',
              borderRadius: '8px',
              border: 'none',
              backgroundColor: activeTab === key ? '#2563eb' : '#f3f4f6',
              color: activeTab === key ? 'white' : '#374151',
              cursor: 'pointer',
              fontSize: '14px',
              fontWeight: '500',
              transition: 'all 0.2s ease',
            }}
          >
            <span style={{ fontSize: '16px' }}>{tab.icon}</span>
            <span>{tab.title}</span>
          </button>
        ))}
      </div>

      {/* Active Tab Content */}
      <div>
        <div style={{ marginBottom: '24px', textAlign: 'center' }}>
          <h3
            style={{
              fontSize: '24px',
              fontWeight: '600',
              color: '#1f2937',
              marginBottom: '8px',
            }}
          >
            {educationalTabs[activeTab].icon} {educationalTabs[activeTab].title}
          </h3>
        </div>

        <div>
          {educationalTabs[activeTab].sections.map((section) => (
            <ExpandableSection
              key={section.id}
              section={section}
              isExpanded={expandedSection === section.id}
              onToggle={() => toggleSection(section.id)}
            />
          ))}
        </div>
      </div>

      {/* Call to Action */}
      <div
        style={{
          backgroundColor: 'white',
          borderRadius: '12px',
          boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
          padding: '24px',
          textAlign: 'center',
          border: '2px solid #e0e7ff',
        }}
      >
        <h4
          style={{
            fontSize: '20px',
            fontWeight: '600',
            color: '#4338ca',
            marginBottom: '12px',
          }}
        >
          🌟 Ready to Apply What You've Learned?
        </h4>
        <p style={{ fontSize: '14px', color: '#6b7280', marginBottom: '16px' }}>
          Knowledge is powerful, but application creates healing. Use our
          journaling and tracking tools to put these principles into practice in
          your daily life.
        </p>
        <div
          style={{
            display: 'flex',
            gap: '12px',
            justifyContent: 'center',
            flexWrap: 'wrap',
          }}
        >
          <span
            style={{
              fontSize: '12px',
              color: '#4338ca',
              backgroundColor: '#eef2ff',
              padding: '6px 12px',
              borderRadius: '16px',
            }}
          >
            📝 Start Journaling
          </span>
          <span
            style={{
              fontSize: '12px',
              color: '#4338ca',
              backgroundColor: '#eef2ff',
              padding: '6px 12px',
              borderRadius: '16px',
            }}
          >
            📊 Track Symptoms
          </span>
          <span
            style={{
              fontSize: '12px',
              color: '#4338ca',
              backgroundColor: '#eef2ff',
              padding: '6px 12px',
              borderRadius: '16px',
            }}
          >
            🎯 Take Assessment
          </span>
        </div>
      </div>
    </div>
  );
};

export default Education;
